name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Swift on Linux
    - uses: sersoft-gmbh/SwiftyActions@v1.3.0
      with:
        release-version: '5.5'
    - name: Run tests
      run: swift test