name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linux:
      runs-on: ubuntu-latest
      strategy:
        fail-fast: false
        matrix:
          image:
            - swiftlang/swift:nightly-5.5
      container: ${{ matrix.image }}
      env:
        LOG_LEVEL: info
      steps:  
        - name: Checkout OneWay
          uses: actions/checkout@v2
        - name: Run base tests with Thread Sanitizer
          run: swift test --enable-test-discovery --sanitize=thread